import pytest

from aoc2024.day08 import *

lower_a = """..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
"""

def test_as():
    antennas = lines_to_grid(lower_a.splitlines())
    assert {3+1j, 6+7j} == find_antinodes(antennas['a'])


upper_a_and_zero = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


upper_a_and_zero_antinodes = """......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....#.....
...#........
#......#....
........A...
.........A..
..........#.
..........#."""

def test_upper_a_and_zero():
    antennas, max_x, max_y = lines_to_grid(upper_a_and_zero.splitlines())
    antinodes = find_antinodes(antennas['A'], max_x, max_y)
    antinodes.update(find_antinodes(antennas['0'], max_x, max_y))
    antinodes_expected, _, _ = lines_to_grid(upper_a_and_zero_antinodes.splitlines())
    assert len(antinodes) == 14
    assert antinodes_expected['#'] == antinodes


all_antinodes = """##....#....#
.#.#....0...
..#.#0....#.
..##...0....
....0....#..
.#...#A....#
...#..#.....
#....#.#....
..#.....A...
....#....A..
.#........#.
...#......##"""

def test_all_antinodes():
    antennas, max_x, max_y = lines_to_grid(upper_a_and_zero.splitlines())
    antinodes = find_all_antinodes(antennas['A'], max_x, max_y)
    antinodes.update(find_all_antinodes(antennas['0'], max_x, max_y))
    antinodes_map, _, _ = lines_to_grid(all_antinodes.splitlines())
    antinodes_expected = set(antinodes_map['#'])
    antinodes_expected.update(antinodes_map['0'])
    antinodes_expected.update(antinodes_map['A'])
    assert 34 == len(antinodes)
    assert antinodes_expected == antinodes
